apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: nie-appt-alerter
build:
  artifacts:
  - image: cdutten/nie-appt-alerter
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/nie-appt-alerter-ns.yaml
    - k8s/nie-appt-alerter-cj.yaml

